theme: jekyll-theme-slate
<!-- link to main stylesheet -->
<link rel="stylesheet" type="text/css" href="/css/main.css">


<!DOCTYPE html>
<html>
<body>

title: Welcome to 14barnesc's homepage!
<h1>My First Heading</h1>
<p>My first paragraph.</p>

</body>
</html>






