theme: jekyll-theme-merlot
<html>
  <head>
    <title>Welcome to my webpage!</title>
   </head>
   <body>
    <h1>This is the Main Heading</h1>
    <p> This is some information talking about the heading topic </p>
   </body>
</html>


